# Generated by Django 4.2.1 on 2023-06-01 19:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_and_time", models.DateTimeField()),
                ("visit_length", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_Name", models.CharField(max_length=64)),
                ("last_Name", models.CharField(max_length=128)),
                ("emailAddress", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254)),
                ("donation", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Schedule_hours",
                    models.FloatField(
                        default=9,
                        validators=[
                            django.core.validators.MaxValueValidator(18.0),
                            django.core.validators.MinValueValidator(9.0),
                        ],
                    ),
                ),
                (
                    "Schedule_days",
                    models.CharField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TherapistSpecialties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialty", models.CharField(max_length=128)),
                ("description", models.TextField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="Therapist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_Name", models.CharField(max_length=64)),
                ("last_Name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("emilAddress", models.EmailField(max_length=254)),
                ("schedule", models.ManyToManyField(to="pogadaj.schedulecalendar")),
                (
                    "specialties",
                    models.ManyToManyField(to="pogadaj.therapistspecialties"),
                ),
                (
                    "therapist_appointment",
                    models.ManyToManyField(
                        through="pogadaj.Appointment", to="pogadaj.client"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pogadaj.client"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="therapist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pogadaj.therapist"
            ),
        ),
    ]
