# Generated by Django 4.2.1 on 2023-06-02 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pogadaj", "0002_aboutus_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="visit_length",
            field=models.PositiveIntegerField(
                default=60,
                validators=[
                    django.core.validators.MinValueValidator(15),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
    ]
