# Generated by Django 4.2.1 on 2023-06-02 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pogadaj", "0003_alter_appointment_visit_length"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="first_Name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="last_Name",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="therapist",
            old_name="emilAddress",
            new_name="emailAddress",
        ),
        migrations.RenameField(
            model_name="therapist",
            old_name="first_Name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="therapist",
            old_name="last_Name",
            new_name="last_name",
        ),
    ]
