# Generated by Django 4.2.1 on 2023-06-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pogadaj", "0005_client_phone_number_therapist_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapist",
            name="specialties",
            field=models.ManyToManyField(null=True, to="pogadaj.therapistspecialties"),
        ),
    ]
